### ISSUE TITLE
mac safari just throws error

### ISSUE THREAD

**Issue by jimmack1963** [kaliatech/web-audio-recording-tests#3]

**Comment by kaliatech** [comment]
> Every few months it seems something changes at apple and these tests stop working from Safari. They usually work from Chrome, at least on my mac mini. This is at least the third time over the past year that this has happened.
> 
> Today I happen to be using Safari 12.1.2 from Mojave 10.14.6.
> 
> Is there a way for me to stay on top of this? Do you usually know in advance that something is changing?

That's a consistent complaint with Apple. They rarely announce changes ahead of time and don't adequately list changes that have been made.  For now, web audio recording, on Safari/Mac, should be considered flaky. Works most of the time, but not all of the time.

I don't know of anyway to stay on top of things beyond actually trying it, which was the original genesis for creating these tests.

**Comment by jimmack1963** [comment]
Thank you Josh.  If my project takes off I'll I'll owe you.

Jim
